/*

 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wipdev.main;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

import com.wipdev.main.game.Game;
import com.wipdev.main.game.commands.CommandHandler;
import com.wipdev.main.io.WebsocketManager;

import io.javalin.Javalin;

public class App {
    
	public static App instance;
	
	private Game game;
	private Javalin javalin;
	
	public App() {
		javalin = Javalin.create()
				.enableStaticFiles("/public")
				.start(8080);
		game = new Game();
		
		init();
		WebsocketManager wsm = new WebsocketManager(javalin,game);
		game.start();
	}
	
	
	
    private void init() {
    	CommandHandler.init();
		
	}

    private void crop() {
    	try {
			BufferedImage image = ImageIO.read(new File("src/main/resources/public/img/tiles/Overworld.png"));
			File folder = new File("src/main/resources/public/img/cropped");
			folder.mkdir();
			int id=0;
			for(int x=0;x<image.getWidth();x+=16) {
				for(int y=0;y<image.getHeight();y+=16) {
					BufferedImage sub = image.getSubimage(x, y, 16, 16);
					File save = new File(folder.getPath()+"/img"+id+".png");
					save.createNewFile();
					ImageIO.write(sub, "png", save);
					id++;
					System.out.println("Created img = "+id);
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
    }

	public static void main(String[] args) {
    	instance = new App();
    }
}
